# SPDX-License-Identifier: Apache-2.0
[package]
name = "nova-ip-platform-linux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0"

[dependencies]
nova-types = { path = "../nova-types" }
nova-interface-ip-platform-attachment = { path = "../nova-interface-ip-platform-attachment" }

[lints]
workspace = true
