[package]
name = "nova-p-rap"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
nova-types = { path = "../nova-types" }
nova-interface-p-path-provider = { path = "../nova-interface-p-path-provider" }
nova-interface-p-rap-binding = { path = "../nova-interface-p-rap-binding" }

[lints]
workspace = true
