# SPDX-License-Identifier: AGPL-3.0-or-later
[package]
name = "nova-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "AGPL-3.0-or-later"

[dependencies]
nova-p-core = { path = "../nova-p-core" }
nova-r-stratum = { path = "../nova-r-stratum" }
nova-o-stratum = { path = "../nova-o-stratum" }

[lints]
workspace = true
