# SPDX-License-Identifier: Apache-2.0
[package]
name = "nova-virtual-fabric"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0"

[dependencies]
nova-interface-virtual-fabric = { path = "../nova-interface-virtual-fabric" }

[lints]
workspace = true
