# SPDX-License-Identifier: AGPL-3.0-or-later
[package]
name = "nova-o-stratum"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "AGPL-3.0-or-later"

[dependencies]
nova-types = { path = "../nova-types" }
nova-interface-r-o = { path = "../nova-interface-r-o" }
nova-interface-o-a = { path = "../nova-interface-o-a" }

[lints]
workspace = true
